import type { Metadata } from "next";
import "./globals.css";
import RainbowslotProvider from "@/components/RainbowSlotProvider";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ids = [1, 2, 3, 4, 5, 6, 7, 8, 9];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="menu">
          {ids.map(id => <Link className="link" href={`/pages/${id}`} key={id}>page {id}</Link>)}
        </div>
        <RainbowslotProvider>
          {children}
        </RainbowslotProvider>
      </body>
    </html>
  );
}
